import { createHash } from "node:crypto";
import { APPROVAL_KEY_MIN_BYTES } from "@kobe/protocol";
import type { ApprovalKey } from "@kobe/protocol/node";

/**
 * The approval HMAC key (D29; KOBE-37). One install-wide secret, `KOBE_APPROVAL_KEY` (generated by
 * the Helm chart into the sandbox session-keys Secret as `approval-hmac`), held by the server, which
 * signs, and by the MCP proxy (KOBE-58), which verifies. It never enters a sandbox.
 *
 * `kid` is derived from the key (`a-` + 12 hex of SHA-256), so a rotated key gets a new kid and a
 * token signed with the old key fails as `unknown_key` instead of `bad_mac`. Rotating the key
 * invalidates approvals allowed but not yet used (their tokens live 10 minutes).
 */

export interface ApprovalKeyring {
  /** Signs new approvals. */
  readonly current: ApprovalKey;
  /** Resolves a token's `kid` (only the current key today). */
  keyFor(kid: string): ApprovalKey | undefined;
}

export function approvalKeyFromSecret(secret: string): ApprovalKey {
  const bytes = new TextEncoder().encode(secret);
  if (bytes.byteLength < APPROVAL_KEY_MIN_BYTES) {
    throw new Error(`the approval key must be at least ${APPROVAL_KEY_MIN_BYTES} bytes`);
  }
  const kid = `a-${createHash("sha256").update(bytes).digest("hex").slice(0, 12)}`;
  return { kid, secret: bytes };
}

export function approvalKeyring(secret: string): ApprovalKeyring {
  const current = approvalKeyFromSecret(secret);
  return {
    current,
    keyFor: (kid) => (kid === current.kid ? current : undefined),
  };
}
