import { randomUUID } from "node:crypto";
import {
  BifrostAdminError,
  vkActive,
  type BifrostAdmin,
  type KeySpec,
  type ObservedCustomer,
  type ObservedProvider,
  type ObservedTeam,
  type ObservedVirtualKey,
  type ProviderSpec,
  type VirtualKeySpec,
} from "../bifrost-admin.js";

interface StoredKey extends KeySpec {
  readonly id: string;
}

/**
 * In-memory Bifrost admin API for tests, with the behaviours the sync relies on, as observed on
 * Bifrost v2.2.5 (docs/ledger/KOBE-40.md): virtual key ids and values are generated by Bifrost,
 * key names are unique across providers, provider names are unique, deleting a provider that
 * virtual keys reference is refused, key values are never returned. `calls` records every write.
 */
export class FakeBifrost implements BifrostAdmin {
  readonly providers = new Map<string, ProviderSpec & { keys: StoredKey[] }>();
  readonly customers = new Map<string, ObservedCustomer>();
  readonly teams = new Map<string, ObservedTeam>();
  readonly virtualKeys = new Map<string, ObservedVirtualKey>();
  readonly calls: string[] = [];
  /**
   * What each provider's list-models API answers (a refresh reads it with the provider's key):
   * model ids, or an error Bifrost records on the provider's keys.
   */
  readonly upstream = new Map<string, readonly string[] | { readonly error: string }>();
  /** Bifrost's model cache per provider (filled by a refresh, or set by a test). */
  readonly liveModels = new Map<string, readonly string[]>();
  /** Input modalities Bifrost reports per provider and model name (KOBE-191). */
  readonly liveModalities = new Map<string, ReadonlyMap<string, readonly string[]>>();
  private readonly discovery = new Map<string, { status: string; description?: string }>();
  /** Make the next calls fail (unreachable) while true. */
  down = false;

  private check(method: string, path: string): void {
    if (this.down) throw new BifrostAdminError(method, path, undefined);
  }

  private reject(method: string, path: string, status = 400): never {
    throw new BifrostAdminError(method, path, status);
  }

  /** Forgets everything (a restarted pod without persistence). */
  wipe(): void {
    this.providers.clear();
    this.customers.clear();
    this.teams.clear();
    this.virtualKeys.clear();
  }

  /** Bifrost's own view of a key value, for assertions (the API never returns it). */
  keyValue(provider: string): string | undefined {
    return this.providers.get(provider)?.keys[0]?.value;
  }

  async listProviders(): Promise<ObservedProvider[]> {
    this.check("GET", "/api/providers");
    return [...this.providers.values()].map((p) => ({
      name: p.name,
      baseUrl: p.baseUrl,
      allowPrivateNetwork: p.allowPrivateNetwork,
      keyless: p.keyless,
      custom: p.custom,
    }));
  }
  async listKeys(provider: string) {
    this.check("GET", `/api/providers/${provider}/keys`);
    const p = this.providers.get(provider) ?? this.reject("GET", "/api/providers/keys", 404);
    const d = this.discovery.get(provider);
    return p.keys.map((k) => ({
      id: k.id,
      name: k.name,
      status: d?.status,
      description: d?.description,
    }));
  }
  async addProvider(spec: ProviderSpec) {
    this.check("POST", "/api/providers");
    if (this.providers.has(spec.name)) this.reject("POST", "/api/providers", 409);
    this.calls.push(`provider.add ${spec.name}`);
    this.providers.set(spec.name, { ...spec, keys: [] });
  }
  async updateProvider(spec: ProviderSpec) {
    this.check("PUT", "/api/providers");
    const p = this.providers.get(spec.name) ?? this.reject("PUT", "/api/providers", 404);
    this.calls.push(`provider.update ${spec.name}`);
    this.providers.set(spec.name, { ...spec, keys: p.keys });
  }
  async deleteProvider(name: string) {
    this.check("DELETE", "/api/providers");
    if (!this.providers.has(name)) this.reject("DELETE", "/api/providers", 404);
    if ([...this.virtualKeys.values()].some((v) => name in v.models)) {
      this.reject("DELETE", "/api/providers", 409);
    }
    this.calls.push(`provider.delete ${name}`);
    this.providers.delete(name);
  }
  async addKey(provider: string, key: KeySpec) {
    this.check("POST", "/api/providers/keys");
    const p = this.providers.get(provider) ?? this.reject("POST", "/api/providers/keys", 404);
    if ([...this.providers.values()].some((o) => o.keys.some((k) => k.name === key.name))) {
      this.reject("POST", "/api/providers/keys", 409);
    }
    if (p.keyless) this.reject("POST", "/api/providers/keys", 400);
    this.calls.push(`key.add ${provider} ${key.name}`);
    p.keys.push({ ...key, id: randomUUID() });
  }
  async deleteKey(provider: string, id: string) {
    this.check("DELETE", "/api/providers/keys");
    const p = this.providers.get(provider) ?? this.reject("DELETE", "/api/providers/keys", 404);
    this.calls.push(`key.delete ${provider}`);
    p.keys = p.keys.filter((k) => k.id !== id);
  }
  async listCustomers() {
    this.check("GET", "/api/governance/customers");
    return [...this.customers.values()];
  }
  async addCustomer(name: string) {
    this.check("POST", "/api/governance/customers");
    const c = { id: randomUUID(), name };
    this.calls.push(`customer.add ${name}`);
    this.customers.set(c.id, c);
    return c;
  }
  async deleteCustomer(id: string) {
    this.check("DELETE", "/api/governance/customers");
    this.calls.push(`customer.delete ${id}`);
    this.customers.delete(id);
  }
  async listTeams() {
    this.check("GET", "/api/governance/teams");
    return [...this.teams.values()];
  }
  async addTeam(name: string, customerId: string) {
    this.check("POST", "/api/governance/teams");
    if (!this.customers.has(customerId)) this.reject("POST", "/api/governance/teams");
    const t = { id: randomUUID(), name, customerId };
    this.calls.push(`team.add ${name}`);
    this.teams.set(t.id, t);
    return t;
  }
  async updateTeam(id: string, customerId: string) {
    this.check("PUT", "/api/governance/teams");
    const t = this.teams.get(id) ?? this.reject("PUT", "/api/governance/teams", 404);
    this.calls.push(`team.update ${t.name}`);
    this.teams.set(id, { ...t, customerId });
  }
  async deleteTeam(id: string) {
    this.check("DELETE", "/api/governance/teams");
    this.calls.push(`team.delete ${this.teams.get(id)?.name ?? id}`);
    this.teams.delete(id);
  }
  async listVirtualKeys() {
    this.check("GET", "/api/governance/virtual-keys");
    return [...this.virtualKeys.values()];
  }
  private stored(spec: VirtualKeySpec, id: string, value: string): ObservedVirtualKey {
    for (const provider of Object.keys(spec.models)) {
      if (!this.providers.has(provider)) this.reject("POST", "/api/governance/virtual-keys");
    }
    if (!this.teams.has(spec.teamId)) this.reject("POST", "/api/governance/virtual-keys");
    return {
      id,
      name: spec.name,
      value,
      isActive: vkActive(spec),
      teamId: spec.teamId,
      models: Object.fromEntries(Object.entries(spec.models).map(([p, m]) => [p, [...m].sort()])),
      allKeys: true,
      requestsPerMinute:
        typeof spec.limits?.rate_limit?.request_max_limit === "number" &&
        spec.limits.rate_limit.request_reset_duration === "1m"
          ? spec.limits.rate_limit.request_max_limit
          : undefined,
    };
  }
  async addVirtualKey(spec: VirtualKeySpec) {
    this.check("POST", "/api/governance/virtual-keys");
    const id = randomUUID();
    const value = `sk-bf-${randomUUID()}`;
    this.virtualKeys.set(id, this.stored(spec, id, value));
    this.calls.push(`vk.add ${spec.name}`);
    return { id, value };
  }
  async updateVirtualKey(id: string, spec: VirtualKeySpec) {
    this.check("PUT", "/api/governance/virtual-keys");
    const v = this.virtualKeys.get(id) ?? this.reject("PUT", "/api/governance/virtual-keys", 404);
    this.virtualKeys.set(id, this.stored(spec, id, v.value));
    this.calls.push(`vk.update ${spec.name}`);
  }
  async listModels(provider: string) {
    this.check("GET", "/api/models");
    return [...(this.liveModels.get(provider) ?? [])];
  }
  async listModelInfo(provider: string) {
    return (await this.listModels(provider)).map((name) => ({
      name,
      inputModalities: this.liveModalities.get(provider)?.get(name) ?? [],
    }));
  }
  async refreshModels(provider: string) {
    this.check("POST", "/api/providers/refresh-models");
    if (!this.providers.has(provider)) this.reject("POST", "/api/providers/refresh-models", 404);
    this.calls.push(`models.refresh ${provider}`);
    const answer = this.upstream.get(provider) ?? [];
    if ("error" in answer) {
      this.discovery.set(provider, { status: "list_models_failed", description: answer.error });
      return;
    }
    this.discovery.set(provider, { status: "success" });
    this.liveModels.set(provider, [...(answer as readonly string[])]);
  }
  async deleteVirtualKey(id: string) {
    this.check("DELETE", "/api/governance/virtual-keys");
    this.calls.push(`vk.delete ${this.virtualKeys.get(id)?.name ?? id}`);
    this.virtualKeys.delete(id);
  }
}
